TAbasdut/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from base.views import index, login, login_request, logout_request, register, add_mahasiswa, select_donatur_type, add_donatur_yayasan, add_donatur_individual


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', index, name='index'),
    url(r'login/$', login, name='login'),

    url(r'login-request/$', login_request, name='login_request'),
    url(r'logout-request/$', logout_request, name='logout_request'),

    url(r'register/$', register, name='register'),
    url(r'register_mahasiswa/$', add_mahasiswa, name = 'add_mahasiswa'),
    url(r'select_donatur_type/$', select_donatur_type, name = 'select_donatur_type'),
    url(r'register_donatur_yayasan/$', add_donatur_yayasan, name='add_donatur_yayasan'),
    url(r'register_donatur_individual/$', add_donatur_individual, name='add_donatur_individual'),


    url(r'^skema_beasiswa/', include(('skema_beasiswa.urls', 'skema_beasiswa'), namespace='skema_beasiswa')),
    url(r'^$', RedirectView.as_view(url = '/index/', permanent = 'true'), name='home'),
]

base/urls.py
from django.conf.urls import url
from .views import index, login, login_request, logout_request

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'login/$', login, name='login'),
    url(r'login-request/$', login_request, name='login_request'),
    url(r'logout-request/$', logout_request, name='logout_request')
]

skema_beasiswa/urls.py
from django.conf.urls import url
from .views import index, add_skema_beasiswa, add_beasiswa, skema_detail, daftar_beasiswa

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_new_schema/$', add_skema_beasiswa, name='add_skema_beasiswa'),
    url(r'add_beasiswa_to_schema/$', add_beasiswa, name='add_beasiswa_to_schema'),
    url(r'skema/(?P<id>\d+)/(?P<nourut>\d+)/$', skema_detail, name="skema_detail"),
    url(r'register_beasiswa/$', daftar_beasiswa, name='daftar_beasiswa'),
]

skema_beasiswa/models.py
from django.db import models

# Create your models here.

skema_beasiswa/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db import connection
from datetime import datetime
import os
import json

response = {}

def index (request):
    #Mengecek post dari user yang menyatakan
    #Apakah yang akan dilakukan oleh donatur?
    if request.method == 'POST':
        if request.POST['donatur_do'] == 'tambah_sb_baru':
            response['flag_new_schema'] = True
            return render (request, 'skema_beasiswa/donatur_do.html', response)
        elif request.POST['donatur_do'] == 'tambah_beasiswa_dari_sb':
            response['flag_new_beasiswa'] = True
            c = connection.cursor()
            c.execute("SELECT kode_skema_beasiswa FROM skema_beasiswa_aktif_skemabeasiswa")
            daftar_kode_beasiswa = dictfetchall(c)
            response['daftar_kode_beasiswa'] = daftar_kode_beasiswa
            return render (request, 'skema_beasiswa/donatur_do.html', response)
    else :
        response['flag_new_schema'] = False
        response['flag_new_beasiswa'] = False
        return render (request, 'skema_beasiswa/what_donatur_do.html', response)

@csrf_exempt
def add_skema_beasiswa (request):
    #Menerima post dari user
    if request.method == 'POST':
        kode_skema_beasiswa = request.POST['kode_skema_beasiswa']
        nama_skema_beasiswa = request.POST['nama_skema_beasiswa']
        jenis_skema_beasiswa = request.POST['jenis_skema_beasiswa']
        deskripsi = request.POST['deskripsi_beasiswa']
        syarat_beasiswa = request.POST['syarat_beasiswa']

        #CEK APAKAH KODE SKEMA BEASISWA TELAH TERDAFTAR DALAM DATABASE SISTEM
        c = connection.cursor()
        c.execute('SELECT kode_skema_beasiswa FROM skema_beasiswa_aktif_skemabeasiswa')
        daftarKodeSkema = dictfetchall(c)
        flagKodeSkema = any(i['kode_skema_beasiswa'] == kode_skema_beasiswa for i in daftarKodeSkema)
        c.close()

        #Jika belum terdaftar, masukkan kode skema beasiswa ke dalam database sistem
        if (not flagKodeSkema):
            nomor_identitas_donatur = request.session['nomor_identitas_donatur']
            c = connection.cursor()
            #Memasukkan skema beasiswa baru ke dalam tabel skema beasiswa
            query = "INSERT INTO skema_beasiswa_aktif_skemabeasiswa VALUES ('%s', '%s', '%s', '%s', '%s')" %\
            (kode_skema_beasiswa, nama_skema_beasiswa, jenis_skema_beasiswa, deskripsi, nomor_identitas_donatur)
            #Memasukkan syarat beasiswa tersebut ke dalam tabel syarat_beasiswa
            query2 = "INSERT INTO skema_beasiswa_aktif_syaratbeasiswa VALUES ('%s', '%s')" %(syarat_beasiswa, kode_skema_beasiswa)
            c.execute(query)
            c.execute(query2)
            c.close()
        return HttpResponseRedirect(reverse('skema_beasiswa:index'))
    else :
        return render (request, 'skema_beasiswa/what_donatur_do.html', request)

@csrf_exempt
def add_beasiswa (request):
    #menerima post data dari user
    if request.method == 'POST':
        postdata_kode_skema_beasiswa = request.POST['kode_skema_beasiswa']
        postdata_nomor_urut = request.POST['no_urut']
        postdata_tgl_mulai_pendaftaran = request.POST['tgl_mulai_pendaftaran']
        postdata_tgl_tutup_pendaftaran = request.POST['tgl_tutup_pendaftaran']
        postdata_periode_penerimaan = 'testing'
        postdata_status = 'ditutup'
        default_jumlah_pendaftar = 0
        nomor_identitas_donatur = request.session['nomor_identitas_donatur']

<<<<<<< HEAD
        #CEK KODE SKEMA DAN NOMOR URUT BERSIFAT UNIK
        c = connection.cursor()
        c.execute("SELECT * FROM skema_beasiswa_aktif_skemabeasiswaaktif")
        daftarKodeSkema = dictfetchall(c)
        flag = False
        for i in daftarKodeSkema :
            if (i['kode_skema_beasiswa_id'] == postdata_kode_skema_beasiswa and i['no_urut'] == postdata_nomor_urut):
                flag = True
        c.close()

        if (not flagKodeSkema) and (not flagNoUrut) :
            testing = 'testing'
            c = connection.cursor()
            query = "INSERT INTO skema_beasiswa_aktif_skemabeasiswaaktif(no_urut, tgl_mulai_pendaftaran, tgl_tutup_pendaftaran, periode_penerimaan, status, jumlah_pendaftar, kode_skema_beasiswa_id) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')" %\
            (postdata_nomor_urut, postdata_tgl_mulai_pendaftaran, postdata_tgl_tutup_pendaftaran, postdata_periode_penerimaan, postdata_status, default_jumlah_pendaftar, postdata_kode_skema_beasiswa)
            print(query)
            c.execute(query)
            c.close()
        return HttpResponseRedirect(reverse('skema_beasiswa:index'))


def skema_detail(request, id, nourut):
    c = connection.cursor()
    c.execute('SELECT * FROM skema_beasiswa_aktif_skemabeasiswaaktif join skema_beasiswa_aktif_skemabeasiswa ON kode_skema_beasiswa_id = kode_skema_beasiswa WHERE kode_skema_beasiswa_id = %s AND no_urut = %s', [id, nourut] )
    data_skema = dictfetchall(c)[0]
    print(data_skema)
    response['data_skema'] = data_skema
    c.close()
    return render(request, 'skema_beasiswa/detail_skema_beasiswa_aktif.html', response)

=======
        #Validasi nomor urut dan kode skema beasiswa bersifat unik, accepted = False jika tidak memenuhi, otherwise
        accepted = not (check_new_packet(postdata_kode_skema_beasiswa, postdata_no_urut))

        if (accepted):
          execute_insert_packet(postdata_kode_skema_beasiswa, postdata_no_urut, postdata_tgl_mulai_pendaftaran, postdata_tgl_tutup_pendaftaran, periode_penerimaan, status, default_jumlah_pendaftar)

        #Jika tidak accepted, tampilkan pesan error seperti yang diminta
        return HttpResponseRedirect(reverse('index'))

#Mengecek status paket beasiswa
def get_status (tgl_mulai_pendaftaran, tgl_tutup_pendaftaran):
    if (datetime.now() > tgl_mulai_pendaftaran and datetime.now() < tgl_tutup_pendaftaran):
        return 'dibuka'
    else :
        return 'ditutup''

#Mengecek apakah no urut dan kode skema beasiswa bersifat unik
def check_new_packet(kode_skema_beasiswa, no_urut):
    packet_ = execute_query("SELECT kode_skema_beasiswa, no_urut FROM skema_beasiswa_aktif WHERE kode_skema_beasiswa = '%s' and no_urut = '%s'" %(kode_skema_beasiswa, no_urut))
    if (packet_['no_urut'] == 'no_urut'):
        return True
    else :
        return False

#Memasukkan skema beasiswa ke dalam database sistem
def execute_insert_skema_beasiswa (kode, nama, jenis, deskripsi, nomor_identitas_donatur):
    execute_insert("INSERT INTO skema_beasiswa VALUES ('%s', '%s', '%s', '%s', '%s')" %(kode, nama, jenis, deskripsi, nomor_identitas_donatur))

#Memasukkan syarat beasiswa ke dalam database sistem
def execute_insert_syarat_beasiswa (kode_beasiswa, syarat):
    execute_insert("INSERT INTO syarat_beasiswa VALUES ('%s', '%s')" %(kode_beasiswa, syarat))

#Fungsi yang mengecek apakah kode skema beasiswa telah terdaftar dalam database sistem
def check_kode_skema_beasiswa (kode_skema_beasiswa):
    kode_skema_beasiswa_ = execute_query("SELECT kode FROM skema_beasiswa WHERE kode = '%s'" %(kode_skema_beasiswa))
    if (kode_skema_beasiswa_['kode'] == kode_skema_beasiswa):
        return True
    else :
        return False

#Mendapatkan seluruh daftar kode skema beasiswa
def get_daftar_kode_skema_beasiswa ():
    cursor = connection.cursor()
    c.execute("SELECT kode FROM skema_beasiswa")
    result = dictfetchall(cursor)
    c.close()
    return result

#Melihat Informasi Beasiswa Aktif - Fitur 4

#Fungsi yang menampilkan detail skema beasiswa tertentu sesuai yang diminta oleh user
def view_schema_detail(request, kode_beasiswa, no_urut):
    response['data_skema'] = execute_query("SELECT nama, tgl_tutup_pendaftaran, status, jumlah_pendaftar FROM skema_beasiswa_aktif JOIN skema_beasiswa ON kode = kode_skema_beasiswa WHERE kode = '%s' and no_urut = '%s'" %(kode_beasiswa, no_urut))
    return render(request, 'skema_beasiswa/detail_skema_beasiswa_aktif.html', response)

#Mendaftar Calon Penerima Beasiswa - Fitur 5

#Fungsi yang dipanggil ketika mahasiswa mendaftar beasiswa melalui form pendaftaran
def register_for_scholarship (npm, kode_skema_beasiswa):
    if request.method == "POST":
        postdata_kode_skema_beasiswa = request.POST['kode_skema_beasiswa']
        postdata_npm = request.POST['npm']
        postdata_email = request.POST['email']
        postdata_ips = request.POST['ips']

        #Validasi NPM dan kode skema beasiswa, has_been_registered = False jika mahasiswa dengan npm = npm belum pernah mendaftar beasiswa dengna kode = kode_skema_beasiswa
        has_been_registered = check_mahasiswa_has_been_registered_for_scholarship(postdata_kode_skema_beasiswa, postdata_npm)

        if not (has_been_registered) :
          execute_insert_pendaftaran(get_no_urut(postdata_kode_skema_beasiswa, postdata_kode_skema_beasiswa, postdata_npm, datetime.now(), 'Berhasil', 'Menunggu'))

#Fungsi yang melakukan cek apakah mahasiswa sudah pernah mendaftar suatu beasiswa
def check_student_has_been_registered_for_scholarship(kode_skema_beasiswa, npm):
    object_for_check = execute_query("SELECT kode_skema_beasiswa FROM pendaftaran WHERE kode_skema_beasiswa = '%s' and npm = '%s'" %(kode_skema_beasiswa, npm))
    if (object_for_check['npm'] == npm):
        return True
    else :
        return False

#Fungsi yang mengambil nomor urut skema beasiswa yang masih aktif dan paling awal
#Misalkan :
#A16 Foundation memiliki dua buah paket beasiswa
#Paket 1 masih dibuka
#Paket 2 masih dibuka
#Maka fungsi mengembalikan nomor urut paket 1 karena paket 1 lebih dulu dibandingkan paket 2
def get_no_urut (kode_skema_beasiswa):
    no_urut_ = execute_query("SELECT no_urut FROM skema_beasiswa_aktif WHERE status = 'dibuka' and kode_skema_beasiswa = '%s' LIMIT 1" %(kode_skema_beasiswa))
    return no_urut_['no_urut']

skema_beasiswa/templates/skema_beasiswa/detail_skema_beasiswa_aktif.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h1>{{ data_skema.nama }} - {{ data_skema.no_urut }}</h1>

    <h3>{{ data_skema.deskripsi }}</h3>
    <h3>Persyaratan :</h3>

    {% if request.session.role == 'mahasiswa' %}
    <a href="{% url 'skema_beasiswa:daftar_beasiswa' %}"><button class="btn btn-primary btn-lg">Daftar</button></a>
    {% endif %}
</div>
{% endblock %}

skema_beasiswa/templates/skema_beasiswa/donatur_do.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
{% if flag_new_beasiswa %}
  <div class="container">
    <div class="judul">
        <h1> FORM PENDAFTARAN TAMBAH BEASISWA DARI PAKET </h1>
    </div>
    <form action="{% url 'skema_beasiswa:add_beasiswa_to_schema' %}" method="POST">
        {% csrf_token %}
        <p>
          <label for="kode_skema_beasiswa"> Kode Beasiswa : </label>
          <select id="kode_skema_beasiswa" name ="kode_skema_beasiswa">
          {% for kode in daftar_kode_beasiswa %}
              <option value = {{kode.kode_skema_beasiswa}}> {{kode.kode_skema_beasiswa}} </option>
          {% endfor %}
          </select>
        </p>
        <p>
          <label for="no_urut"> Nomor Urut : </label>
          <input type="text" id="no_urut" name="no_urut" required>
        </p>
        <p>
          <label for="tgl_mulai_pendaftaran"> Tanggal Mulai Pendaftaran : </label>
          <input type="datetime-local" id="tgl_mulai_pendaftaran" name="tgl_mulai_pendaftaran">
        </p>
        <p>
          <label for="tgl_tutup_pendaftaran"> Tanggal Tutup Pendaftaran : </label>
          <input type="datetime-local" id="tgl_tutup_pendaftaran" name='tgl_tutup_pendaftaran'/>
        </p>
        <button type="submit" class="btn btn-primary">Choose</button>
    </form>
  </div>
{% endif %}
{% if flag_new_schema %}
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
          <div class="rata-tengah">
              <div class="judul">
                  <h1> FORM PENDAFTARAN PAKET BEASISWA </h1>
              </div>
              <form action="{% url 'skema_beasiswa:add_skema_beasiswa' %}" method="POST">
                  {% csrf_token %}
                  <p>
                    <label for="kode_skema_beasiswa"> Kode : </label>
                    <input type="text" id="kode_skema_beasiswa" name="kode_skema_beasiswa" required>
                  </p>
                  <p>
                    <label for="nama_skema_beasiswa"> Nama Paket Beasiswa : </label>
                    <input type="text" id="nama_skema_beasiswa" name="nama_skema_beasiswa" required>
                  </p>
                  <p>
                      <label for="jenis_skema_beasiswa"> Jenis Paket Beasiswa : </label>
                      <select id="jenis_skema_beasiswa" name ="jenis_skema_beasiswa">
                        <option value = "bantuan"> Bantuan </option>
                        <option value = "penelitian"> Penelitian </option>
                        <option value = "prestasi"> Prestasi </option>
                        <option value = "akademik"> Akademik </option>
                      </select>
                  </p>
                  <p>
                    <label for="deskripsi_beasiswa"> Deskripsi : </label>
                    <input type="text" id="deskripsi_beasiswa" name="deskripsi_beasiswa" rows = "3" required>
                  </p>
                  <p>
                    <label for="syarat_beasiswa"> Syarat Beasiswa : </label>
                    <input type="text" id="syarat_beasiswa" name="syarat_beasiswa" rows = "3" required>
                  </p>
                  <button type="submit" class="btn btn-primary">Submit</button>
              </form>
          </div>
      </div>
  </div>
{% endif %}
{% endblock %}

{% block javascript%}
  <script type="text/javascript">
    $(function() {
      $('#datetimepicker').datetimepicker();
    });
  </script>
{% endblock %}

skema_beasiswa/templates/skema_beasiswa/form_pendaftaran_beasiswa.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> FORM PENDAFTARAN BEASISWA </h1>
            </div>
            <form action="{% url 'skema_beasiswa:daftar_beasiswa' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="kode_skema_beasiswa"> Kode Beasiswa : </label>
                    <select id="kode_skema_beasiswa" name="kode_skema_beasiswa">
                    {% for kode in daftar_kode_beasiswa %}
                      <option value= {{kode.kode_skema_beasiswa}}> </option>
                    {% endfor %}
                    </select>
                  </p>
                  <p>
                    <label for="npm"> NPM : </label>
                    <input value = {{npm_pendaftar}} disabled></input>
                  </p>
                  <p>
                    <label for="email"> Email : </label>
                    <input value = {{email_pendaftar}} disabled></input>
                  </p>
                <button type="submit" class="btn btn-primary">Choose</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

skema_beasiswa/templates/skema_beasiswa/tambah_beasiswa_dari_sb.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> FORM PENDAFTARAN TAMBAH BEASISWA DARI PAKET </h1>
            </div>
            <form action="{% url 'skema_beasiswa_aktif:add_beasiswa' %}" method="POST">
                {% csrf_token %}
                <p>
                  <label for="kode_skema_beasiswa"> Kode Beasiswa : </label>
                  <input type="text" id="kode_skema_beasiswa" name="kode_skema_beasiswa" required>
                </p>
                <p>
                  <label for="nama_paket_beasiswa"> Nama Paket Beasiswa : </label>
                  <input type="text" id="nama_paket_beasiswa" name="nama_paket_beasiswa" required>
                </p>
                <p>
                    <label for="jenis_paket_beasiswa"> Jenis Paket Beasiswa : </label>
                    <select id="jenis_paket_beasiswa" name ="jenis_paket_beasiswa">
                      <option value = "bantuan"> Bantuan </option>
                      <option value = "penelitian"> Penelitian </option>
                      <option value = "prestasi"> Prestasi </option>
                      <option value = "akademik"> Akademik </option>
                    </select>
                </p>
                <p>
                  <label for="deskripsi_beasiswa"> Deskripsi : </label>
                  <input type="text" id="deskripsi_beasiswa" name="deskripsi_beasiswa" rows = "3" required>
                </p>
                <p>
                  <label for="syarat_beasiswa"> Syarat Beasiswa : </label>
                  <input type="text" id="syarat_beasiswa" name="syarat_beasiswa" rows = "3" required>
                </p>
                <button type="submit" class="btn btn-primary">Choose</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

skema_beasiswa/templates/skema_beasiswa/what_donatur_do.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> DONATUR DO? </h1>
                <p class="text-info"> Choose what donatur do? </p>
            </div>
            <form action="{% url 'skema_beasiswa:index' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="donatur_do"> Apa yang dilakukan oleh Donatur? </label>
                    <select id="donatur_do" name ="donatur_do">
                      <option value = "tambah_sb_baru"> Tambah Skema Beasiswa Baru </option>
                      <option value = "tambah_beasiswa_dari_sb"> Tambah Beasiswa Baru dari Paket </option>
                    </select>
                </p>
                <button type="submit" class="btn btn-primary">Choose</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}