TAbasdut/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
from base.views import index, login, login_request, logout_request, register, add_mahasiswa, select_donatur_type, add_donatur_yayasan, add_donatur_individual


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', index, name='index'),
    url(r'login/$', login, name='login'),

    url(r'login-request/$', login_request, name='login_request'),
    url(r'logout-request/$', logout_request, name='logout_request'),

    url(r'register/$', register, name='register'),
    url(r'register_mahasiswa/$', add_mahasiswa, name = 'add_mahasiswa'),
    url(r'select_donatur_type/$', select_donatur_type, name = 'select_donatur_type'),
    url(r'register_donatur_yayasan/$', add_donatur_yayasan, name='add_donatur_yayasan'),
    url(r'register_donatur_individual/$', add_donatur_individual, name='add_donatur_individual'),


    url(r'^skema_beasiswa/', include(('skema_beasiswa.urls', 'skema_beasiswa'), namespace='skema_beasiswa')),
    url(r'^$', RedirectView.as_view(url = '/index/', permanent = 'true'), name='home'),
]

base/urls.py
from django.conf.urls import url
from .views import index, login, login_request, logout_request

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'login/$', login, name='login'),
    url(r'login-request/$', login_request, name='login_request'),
    url(r'logout-request/$', logout_request, name='logout_request')
]

skema_beasiswa/urls.py
from django.conf.urls import url
from .views import index, add_skema_beasiswa, add_beasiswa, skema_detail, daftar_beasiswa

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_new_schema/$', add_skema_beasiswa, name='add_skema_beasiswa'),
    url(r'add_beasiswa_to_schema/$', add_beasiswa, name='add_beasiswa_to_schema'),
    url(r'skema/(?P<id>\d+)/(?P<nourut>\d+)/$', skema_detail, name="skema_detail"),
    url(r'register_beasiswa/$', daftar_beasiswa, name='daftar_beasiswa'),
]

base/models.py
from django.db import models

class Pengguna(models.Model):
    username = models.CharField(max_length = 20, primary_key = True)
    password = models.CharField(max_length = 20)
    role = models.CharField(max_length = 9)

class Mahasiswa(models.Model):
    npm = models.CharField(max_length = 20, primary_key = True)
    email = models.EmailField(max_length = 50)
    nama = models.CharField(max_length = 50)
    no_telp = models.CharField(max_length = 20, blank = True)
    alamat_tinggal = models.CharField(max_length = 50)
    alamat_domisili = models.CharField(max_length = 50)
    nama_bank = models.CharField(max_length = 50)
    no_rekening = models.CharField(max_length = 20)
    nama_pemilik = models.CharField(max_length = 20)
    username = models.ForeignKey(Pengguna, related_name = 'username_mahasiswa', on_delete = models.CASCADE)

class Donatur(models.Model):
    nomor_identitas = models.CharField(max_length = 20, primary_key = True)
    email = models.EmailField(max_length = 50)
    nama = models.CharField(max_length = 50)
    npwp = models.CharField(max_length = 20)
    no_telp = models.CharField (max_length = 20, blank = True)
    alamat = models.CharField (max_length = 50)
    username = models.ForeignKey(Pengguna, related_name = 'username_donatur', on_delete = models.CASCADE)

class Individual_Donor(models.Model):
    nik = models.CharField(max_length = 16, primary_key = True)
    nomor_identitas_donatur = models.ForeignKey(Donatur, related_name = 'nomoridentitasdonaturindividual', on_delete = models.CASCADE)

class Yayasan (models.Model):
    no_sk_yayasan = models.CharField(max_length = 20, primary_key = True)
    email = models.EmailField(max_length = 50)
    nama = models.CharField (max_length = 50)
    no_telp_cp = models.CharField(max_length = 20, blank = True)
    nomor_identitas_donatur = models.ForeignKey(Donatur, related_name = 'nomoridentitasdonaturyayasan', on_delete = models.CASCADE)

base/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db import connection
from skema_beasiswa.views import dictfetchall
import os
import json

response = {}

def index (request):
    cursor = connection.cursor()
    response['list_beasiswa_aktif'] = fetch_skema_beassiwa_aktif()
    return render(request, 'base/home.html', response)

def login (request):
    if ('username' in request.session):
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request, 'base/login.html', response)

def login_request (request):
    if (request.method == 'POST'):
        postdata_username = request.POST['username']
        postdata_password = request.POST['password']

        cursor = connection.cursor()
        cursor.execute('SELECT * FROM register_pengguna WHERE username = %s', [postdata_username])
        data_pengguna = dictfetchall(cursor)[0]

        if (data_pengguna['password'] == postdata_password):
            request.session['username'] = data_pengguna['username']
            request.session['password'] = data_pengguna['password']
            request.session['role'] = data_pengguna['role']

            if (request.session['role'] == 'donatur') :
                c = connection.cursor()
                c.execute("SELECT nomor_identitas FROM register_donatur WHERE username_id = '%s'" %(postdata_username))
                no_id_donatur = dictfetchall(c)[0]
                request.session['nomor_identitas_donatur'] = no_id_donatur['nomor_identitas']
            response['username'] = data_pengguna['username']
            response['role'] = data_pengguna['role']
            return HttpResponseRedirect(reverse('index'))
    return HttpResponseRedirect(reverse('login'))

def logout_request (request):
    request.session.flush()
    return HttpResponseRedirect(reverse('index'))














############ util
def dictfetchall(cursor):
    desc = cursor.description
    return [
            dict(zip([col[0] for col in desc], row))
            for row in cursor.fetchall()
    ]

def fetch_skema_beassiwa_aktif ():
    cursor = connection.cursor()
    cursor.execute('SELECT * FROM skema_beasiswa_aktif_skemabeasiswaaktif join skema_beasiswa_aktif_skemabeasiswa ON kode_skema_beasiswa_id = kode_skema_beasiswa')
    return dictfetchall(cursor)


############## register

def register (request):
    if request.method == 'POST':
        if request.POST['selected_role'] == 'mahasiswa':
            response['role'] = request.POST['selected_role']
            return render (request, 'base/register_mahasiswa.html', response)
        elif request.POST['selected_role'] == 'donatur':
            return render (request, 'base/register_pilih_tipe_donatur.html', response)
    else :
        return render (request, 'base/register_pilih_role.html', response)

@csrf_exempt
def add_mahasiswa (request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        npm = request.POST['npm']
        email = request.POST['email']
        nama = request.POST['nama']
        no_telp = request.POST['no_telp']
        alamat_tinggal = request.POST['alamat_tinggal']
        alamat_domisili = request.POST['alamat_domisili']
        nama_bank = request.POST['nama_bank']
        no_rekening = request.POST['no_rekening']
        nama_pemilik = request.POST['nama_pemilik']

        #CEK USERNAME DI DAFTAR USER
        c = connection.cursor()
        c.execute("SELECT username FROM register_pengguna")
        daftarPengguna = dictfetchall(c)
        c.execute("SELECT npm FROM register_mahasiswa")
        daftarMahasiswa = dictfetchall(c)
        c.close()

        flagUsername = any(i['username'] == username for i in daftarPengguna)
        flagNpm = any(j['npm'] == npm for j in daftarMahasiswa)

        #for daftar_nama_pengguna in daftarPengguna :
            #if username == daftar_nama_pengguna:
            #    flagUsername = True

        #Check that password have minimal eight character and any digit there
        flagPassword = any(i.isdigit() for i in password) and len(password) > 7

        if (not flagUsername) and flagPassword and (not flagNpm) :
            c = connection.cursor()
            query = "INSERT INTO register_pengguna VALUES ('%s', '%s', 'mahasiswa')" %\
            (username, password)
            c.execute(query)

            query = "INSERT INTO register_mahasiswa VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')" %\
            (npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username)
            c.execute(query)
            c.close()
        return HttpResponseRedirect(reverse('index'))

def select_donatur_type(request):
    if request.method == 'POST':
        if request.POST['selected_donatur_type'] == 'individual':
            response['donatur_type'] = request.POST['selected_donatur_type']
            return render (request, 'base/register_donatur.html', response)
        elif request.POST['selected_donatur_type'] == 'yayasan':
            response['donatur_type'] = request.POST['selected_donatur_type']
            return render (request, 'base/register_donatur.html', response)

@csrf_exempt
def add_donatur_individual(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nik = request.POST['nik']
        email = request.POST['email']
        nama = request.POST['nama']
        npwp = request.POST['npwp']
        no_telp = request.POST['no_telp']
        alamat = request.POST['alamat']

        #CEK USERNAME BELUM TERDAFTAR
        #Cek jumlah karakter pada password adalah minimal 8 karakter
        c = connection.cursor()
        c.execute("SELECT username FROM register_pengguna")
        daftarPengguna = dictfetchall(c)
        flagUsername = any(i['username'] == username for i in daftarPengguna)

        c.execute("SELECT nomor_identitas FROM register_donatur")
        daftarNomorIdentitas = dictfetchall(c)

        c.close()

        flagNomorIdentitas = any(j['nomor_identitas'] == nomor_identitas for j in daftarNomorIdentitas)

        #Check that password have minimal eight character and any digit there
        flagPassword = any(i.isdigit() for i in password) and len(password) > 7

        if (not flagUsername) and flagPassword and (not flagNomorIdentitas) :
            c = connection.cursor()
            query = "INSERT INTO register_pengguna VALUES ('%s', '%s', 'donatur')" %\
            (username, password)
            c.execute(query)
            c.close()

        #Cek Apakah nomor Identitas Donatur sudah terdaftar
        #Cek apakah nik donatur sudah terdaftar
        #Cek apakah jumlah karakter NIK donatur adalah tepat 16 buah

        c = connection.cursor()
        c.execute("SELECT nik FROM register_individual_donor")
        daftarNIK = dictfetchall(c)
        c.close()
        flagNIK = any(k['nik'] == nik for k in daftarNIK)
        flagNIK_jumlah_karakter = len(nik) == 16

        if (not flagNIK and flagNIK_jumlah_karakter ):
            c = connection.cursor()
            query = "INSERT INTO register_donatur VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')" %\
            (nomor_identitas, email, nama, npwp, no_telp, alamat, username)
            query2 = "INSERT INTO register_individual_donor VALUES ('%s', '%s')" %\
            (nik, nomor_identitas)
            c.execute(query)
            c.execute(query2)
            c.close()

        return HttpResponseRedirect(reverse('index'))

@csrf_exempt
def add_donatur_yayasan (request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nomor_sk_yayasan = request.POST['nomor_sk_yayasan']
        email = request.POST['email']
        nama = request.POST['nama']
        no_telp = request.POST['no_telp']
        npwp = request.POST['npwp']
        alamat = request.POST['alamat']

        #CEK USERNAME BELUM TERDAFTAR
        #Cek jumlah karakter pada password adalah minimal 8 karakter
        c = connection.cursor()
        c.execute("SELECT username FROM register_pengguna")
        daftarPengguna = dictfetchall(c)

        flagUsername = any(i['username'] == username for i in daftarPengguna)

        c.execute("SELECT nomor_identitas FROM register_donatur")
        daftarNomorIdentitas = dictfetchall(c)

        flagNomorIdentitas = any(j['nomor_identitas'] == nomor_identitas for j in daftarNomorIdentitas)
        c.close()

        #Check that password have minimal eight character and any digit there
        flagPassword = any(i.isdigit() for i in password) and len(password) > 7

        if (not flagUsername) and flagPassword and (not flagNomorIdentitas) :
            c = connection.cursor()
            query = "INSERT INTO register_pengguna VALUES ('%s', '%s', 'donatur')" %\
            (username, password)
            c.execute(query)
            c.close()

        c = connection.cursor()
        c.execute("SELECT no_sk_yayasan FROM register_yayasan")
        daftar_nomor_SK_yayasan = dictfetchall(c)
        flagSK = any(k['no_sk_yayasan'] == nomor_sk_yayasan for k in daftar_nomor_SK_yayasan)

        if (not flagSK):
            c = connection.cursor()
            query = "INSERT INTO register_donatur VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')" %\
            (nomor_identitas, email, nama, npwp, no_telp, alamat, username)
            query2 = "INSERT INTO register_yayasan VALUES ('%s', '%s', '%s', '%s', '%s')" %\
            (nomor_sk_yayasan, email, nama, no_telp, nomor_identitas)
            c.execute(query)

base/templates/base/home.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <table class="table">
        <thead>
        <th> No</th>
        <th> Nama Beasiswa </th>
        <th> Waktu Tutup Pendaftaran</th>
        <th> Status Beasiswa </th>
        <th> Jumlah Pendaftar </th>
        <th> Detail </th>    
      </thead>
      <tbody>
      {% for paketbeasiswa in list_beasiswa_aktif %}
      <tr>
          <td> {{ forloop.counter }}</td>
          <td> {{ paketbeasiswa.nama }} </td>
          <td> {{ paketbeasiswa.tgl_tutup_pendaftaran }}</td>
          <td> {{ paketbeasiswa.status}}</td>
          <td> {{ paketbeasiswa.jumlah_pendaftar}}</td>
          <td> <a href="{% url 'skema_beasiswa:skema_detail' paketbeasiswa.kode_skema_beasiswa_id paketbeasiswa.no_urut %}"><buton class="btn-primary">see more</buton></a> </td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
</div>

{% endblock %}

base/templates/base/login.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container content-center">
    <div class="container-sm">
        <div class="judul">
            <h1> LOGIN </h1>
            <p class="text-info"> Use your <b> SIMBION's account </b> to LOGIN </p>
        </div>
        <form action="{% url 'login_request' %}" method="POST">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-grou-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">@</span>
                </div>
                <input class="form-control" type="text" id="username" name="username" required>
            </div>
            <div class="input-group mb-3">
                <input class="form-control" type="password" id="password" name="password" placeholder="password" required>
            </div>
            <div>
              <a href = "/register/"><p> Don't have an account? </p> </a>
            </div
            <button type="submit" class="btn btn-primary flex-end">Login</button>
        </form>
    </div>
</div>
{% endblock %}

base/templates/base/register_donatur.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container">
            <div class="judul">
                <h1> REGISTER DONATUR</h1>
                <p class="text-info"> Register as donatur </p>
            </div>
            {% if donatur_type == 'individual' %}
              <form action="{% url 'add_donatur_individual' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="username"> Username : </label>
                      <input class="form-control" type="text" id="username" name="username" required>
                  </div>
                  <div class="form-group">
                      <label for="password"> Password : </label>
                      <input class="form-control" type="password" id="password" name="password" required>
                  </div>
                  <div class="form-group">
                      <label for="nomor_identitas"> Nomor Identitas : </label>
                      <input class="form-control" type="text" id="nomor_identitas" name="nomor_identitas" required>
                  </div>
                  <div class="form-group">
                      <label for="nik"> NIK : </label>
                      <input class="form-control" type="text" id="nik" name="nik" required>
                  </div>
                  <div class="form-group">
                      <label for="email"> Email : </label>
                      <input class="form-control" type="email" id="email" name="email" required>
                  </div>
                  <div class="form-group">
                      <label for="nama"> Nama Lengkap : </label>
                      <input class="form-control" type="text" id="nama" name="nama">
                  </div>
                  <div class="form-group">
                      <label for="npwp"> NPWP : </label>
                      <input class="form-control" type="text" id="npwp" name="npwp" required>
                  </div>
                  <div class="form-group">
                      <label for="no_telp"> Nomor Telepon : </label>
                      <input class="form-control" type="text" id="no_telp" name="no_telp" required>
                  </div>
                  <div class="form-group">
                      <label for="alamat"> Alamat : </label>
                      <input class="form-control" type="text" id="alamat" name="alamat" required>
                  </div>
                  <button type="submit" class="btn btn-primary">Sign Up</button>
              </form>
            {% else %}
              <form action="{% url 'add_donatur_yayasan' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="username"> Username : </label>
                      <input class="form-control" type="text" id="username" name="username" required>
                  </div>
                  <div class="form-group">
                      <label for="password"> Password : </label>
                      <input class="form-control" type="password" id="password" name="password" required>
                  </div>
                  <div class="form-group">
                      <label for="nomor_identitas"> Nomor Identitas : </label>
                      <input class="form-control" type="text" id="nomor_identitas" name="nomor_identitas" required>
                  </div>
                  <div class="form-group">
                      <label for="nomor_sk_yayasan"> Nomor SK Yayasan : </label>
                      <input class="form-control" type="text" id="nomor_sk_yayasan" name="nomor_sk_yayasan" required>
                  </div>
                  <div class="form-group">
                      <label for=""> Email : </label>
                      <input class="form-control" type="email" id="email" name="email" required>
                  </div>
                  <div class="form-group">
                      <label for="nama"> Nama Yayasan : </label>
                      <input class="form-control" type="text" id="nama" name="nama">
                  </div>
                  <div class="form-group">
                      <label for="no_telp"> Nomor Telepon Contact Person : </label>
                      <input class="form-control" type="text" id="no_telp" name="no_telp" required>
                  </div>
                  <div class="form-group">
                      <label for="npwp"> NPWP : </label>
                      <input class="form-control" type="text" id="npwp" name="npwp" required>
                  </div>
                  <div class="form-group">
                      <label for="alamat"> Alamat Yayasan : </label>
                      <input class="form-control" type="text" id="alamat" name="alamat" required>
                  </div>
                  <button type="submit" class="btn btn-primary">Sign Up</button>
              </form>
            {% endif %}
            <br>
            <br>
            <br>
</div>
{% endblock %}

base/templates/base/register_mahasiswa.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container">
            <div class="judul">
                <h1> REGISTER </h1>
                <p class="text-info"> as <b> Mahasiswa </b></p>
            </div>
            <form action="{% url 'add_mahasiswa' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username"> Username </label>
                    <input class="form-control" type="text" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="password"> Password </label>
                    <input class="form-control" type="password" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label for="npm"> NPM :</label>
                    <input class="form-control" type="text" id="npm" name="npm" required>
                </div>
                <div class="form-group">
                    <label for="email"> Email :</label>
                    <input class="form-control" type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="nama"> Nama Lengkap : </label>
                    <input class="form-control" type="text" id="nama" name="nama" required>
                </div>
                <div class="form-group">
                    <label for="no_telp"> Nomor Telepon : </label>
                    <input class="form-control" type="text" id="no_telp" name="no_telp">
                </div>
                <div class="form-group">
                    <label for="alamat_tinggal"> Alamat Tempat Tinggal : </label>
                    <input class="form-control" type="text" id="alamat_tinggal" name="alamat_tinggal" required>
                </div>
                <div class="form-group">
                    <label for="alamat_domisili"> Alamat Domisili : </label>
                    <input class="form-control" type="text" id="alamat_domisili" name="alamat_domisili" required>
                </div>
                <div class="form-group">
                    <label for="nama_bank"> Instansi Bank : </label>
                    <input class="form-control" type="text" id="nama_bank" name="nama_bank" required>
                </div>
                <div class="form-group">
                    <label for="no_rekening"> Nomor Rekening : </label>
                    <input class="form-control" type="text" id="no_rekening" name="no_rekening" required>
                </div>
                <div class="form-group">
                    <label for="nama_pemilik"> Nama Pemilik : </label>
                    <input class="form-control" type="text" id="nama_pemilik" name="nama_pemilik" required>
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <br>
            <br>
            <br>
</div>
{% endblock %}

base/templates/base/register_pilih_role.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="judul">
        <h1>Register </h1>
    </div>
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="selected_role"> Select your Role </label>
            <select class="form-control" id="selected_role" name ="selected_role">
                <option value = "donatur"> Donatur </option>
                <option value = "mahasiswa"> Mahasiswa </option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Choose</button>
    </form>
</div>
{% endblock %}

base/templates/base/register_pilih_tipe_donatur.html
{% extends "base/layout/base.html" %}
{% load static %}
{% block content %}
<div class="container">
            <div class="judul">
                <h1> TIPE DONATUR </h1>
                <p class="text-info"> Choose donatur type </p>
            </div>
            <form action="{% url 'select_donatur_type' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="selected_donatur_type"> Select tipe Donatur </label>
                    <select class="form-control" id="selected_donatur_type" name ="selected_donatur_type">
                      <option value = "individual"> Individual </option>
                      <option value = "yayasan"> Yayasan </option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Choose</button>
            </form>
</div>
{% endblock %}